### ISSUE TITLE
Couldn't generate crate for qt_gui.

### ISSUE THREAD

**Issue by o01eg** [rust-qt/ritual#60]
rust version 1.21.0
clang 5.0.0.
Qt 5.7.1
MS VS 2017

I deleted `-fPIC` flag so qt_core was generated successfully.

```
Generating crate: qt_gui
Loading dependencies
Loading files from D:\devel\qt-cache\qt_core
Running C++ parser
clang version 5.0.0 (tags/RELEASE_500/final)
Initializing clang...
Warning: CLANG_SYSTEM_INCLUDE_PATH environment variable is not set.
This may result in parse errors related to system header includes.
clang arguments: ["-Xclang", "-detailed-preprocessing-record", "-fcxx-exceptions
", "-std=c++14", "-I", "D:/Qt/Qt5.7.1/5.7/msvc2015_64/include", "-I", "D:/Qt/Qt5
.7.1/5.7/msvc2015_64/include\\QtGui", "-I", "D:/Qt/Qt5.7.1/5.7/msvc2015_64/inclu
de\\QtCore"]
Error:
   0: fatal clang error:
D:/Qt/Qt5.7.1/5.7/msvc2015_64/include\QtGui/qimage.h:275:62: error: rvalue refer
ence to type 'QImage' cannot bind to lvalue of type 'QImage'
D:/Qt/Qt5.7.1/5.7/msvc2015_64/include\QtGui/qimage.h:279:40: error: rvalue refer
ence to type 'QImage' cannot bind to lvalue of type 'QImage'
   1: C++ parser failed
error: process didn't exit successfully: `target\release\qt_generator.exe -c D:\
devel\qt-cache -C 3 -l all --debug-logging save -o D:\devel\qt-rust-test01\` (ex
it code: 1)
```

**Comment by Riateche** [comment]
The related [Qt issue](https://bugreports.qt.io/browse/QTBUG-59190) is marked as fixed in Qt 5.9.0. Does the generator work with Qt 5.9 for you?

**Comment by o01eg** [comment]
Yep, `qt_gui` successfully generated for Qt 5.9.2. I wonder if compatibility issues between dependencies should be noticed somewhere.

**Comment by Riateche** [comment]
Using `clang` on MSVC often produces issues. Some versions of `clang` even refuse to parse the standard library headers of some versions of MSVC.
