### ISSUE TITLE
Cannot Compile on WIndows with MSVC 19.41.34120.0?

### ISSUE THREAD

**Issue by FrederikLauber** [rust-qt/ritual#133]
Hi,

working on my first Rust+QT app and I cannot get qt_gui to compile.

Setup is Qt5.14.0 in global PATH, open the Visual Studio Dev prompt -> "cargo run"

If I understand it, this is the issue:

```
[ 75%] Building CXX object CMakeFiles/qt_gui_c.dir/file1.cpp.obj
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\qt_gui_c.dir\file1.cpp.obj.d --working-dir=C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build --filter-prefix="Hinweis: Einlesen der Datei: " -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x86\cl.exe @C:\Users\Freddy\AppData\Local\Temp\nm5BBD.tmp
  file1.cpp
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_gui-0.5.0\c_lib\file1.cpp(54183): error C2664: "void QOpenGLExtraFunctions::glDebugMessageCallback(GLDEBUGPROC,const void *)" : Konvertierung von Argument 1 von "void (__cdecl *)(unsigned int,unsigned int,unsigned int,unsigned int,int,const char *,const void *)" in "GLDEBUGPROC" nicht möglich
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_gui-0.5.0\c_lib\file1.cpp(54183): note: Diese Konvertierung erfordert eine reinterpret_cast-Umwandlung, eine C-Stil-Umwandlung oder eine in Klammern gesetzte Umwandlung im Funktionsstil.
  C:\Qt\Qt5.14.0\5.14.0\msvc2017_64\include\QtGui\qopenglextrafunctions.h(2213): note: Siehe Deklaration von "QOpenGLExtraFunctions::glDebugMessageCallback"
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_gui-0.5.0\c_lib\file1.cpp(54183): note: bei Anpassung der Argumentliste "(void (__cdecl *)(unsigned int,unsigned int,unsigned int,unsigned int,int,const char *,const void *), const void *)"

```

Looking this up brings me to this here: https://stackoverflow.com/questions/55755492/function-unable-to-match-gldebugproc-only-on-msvc-uses-same-glew-version-2-1-0 which recommends adding a "GLAPIENTRY" to the file? But that is an 5 year old issue, that should be fixed long ago, no?

Maybe someone ios nice enough to give me a hint what is goind on here?
Below you find the full log.


Cargo.toml

```
[dependencies]
ndarray = { version = "0.16.1" }
ndarray-rand = {version = "0.15.0"}
rand = "0.8.5"

cxx = { version = "1.0.128" }
cxx-qt = { version = "0.6.1" }
cxx-qt-lib = { version = "0.6.1" }
cpp_core = { version = "0.6.0"}
qt_core = { version = "0.5.0"}
qt_widgets = { version = "0.5.0"}
qt_ui_tools = { version = "0.5.0"}


[build-dependencies]
cxx-qt-build = { version = "0.6.1" }
ruic = "0.1.1"
```

Full Output from build
```
C:\Users\Freddy\RustroverProjects\isospin_simulation>cargo run
   Compiling qt_core v0.5.0
   Compiling qt_gui v0.5.0
error: failed to run custom build command for `qt_core v0.5.0`                                                                                                                                                                                                                                                     

Caused by:
  process didn't exit successfully: `C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-eecb46822d61fad5\build-script-build` (exit code: 1)
  --- stdout
  Current target is unknown: v5.14.0 on x86_64-windows-windows-msvc
  Known targets:
  * v5.9.7 on x86_64-linux-unix-gnu
  * v5.11.3 on x86_64-linux-unix-gnu
  * v5.12.2 on x86_64-linux-unix-gnu
  * v5.13.0 on x86_64-linux-unix-gnu
  * v5.14.0 on x86_64-linux-unix-gnu
  -- RITUAL_INCLUDE_PATH=C:/Qt/Qt5.14.0/5.14.0/msvc2017_64/include;C:/Qt/Qt5.14.0/5.14.0/msvc2017_64/include\QtCore
  -- RITUAL_LIBRARY_PATH=C:/Qt/Qt5.14.0/5.14.0/msvc2017_64/lib
  -- RITUAL_LIBRARY_TYPE=STATIC
  -- RITUAL_LINKED_LIBS=Qt5Core
  -- RITUAL_CPP_LIB_VERSION=51400
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: C:/Users/Freddy/RustroverProjects/isospin_simulation/target/debug/build/qt_core-5c4e8579972aed4a/out/c_lib_build
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\Makefile2 /nologo -L                  clean
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_core_c.dir\build.make /nologo -L                  CMakeFiles\qt_core_c.dir\clean
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -P CMakeFiles\qt_core_c.dir\cmake_clean.cmake
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_core_c_autogen.dir\build.make /nologo -L                  CMakeFiles\qt_core_c_autogen.dir\clean
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -P CMakeFiles\qt_core_c_autogen.dir\cmake_clean.cmake
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -SC:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib -BC:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build --check-build-system CMakeFiles\Makefile.cmake 0
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_progress_start C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build\CMakeFiles C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build\\CMakeFiles\progress.marks
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\Makefile2 /nologo -L                  all
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_core_c_autogen.dir\build.make /nologo -L                  CMakeFiles\qt_core_c_autogen.dir\depend
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_depends "NMake Makefiles" C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib C:\Users\Freddy\.cargo\registry\src\index.crates.io-6
f17d22bba15001f\qt_core-0.5.0\c_lib C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build\CMakeFiles\qt_core_c_autogen.dir\DependInfo.cmake "--color="
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_core_c_autogen.dir\build.make /nologo -L                  CMakeFiles\qt_core_c_autogen.dir\build
  [ 25%] Automatic MOC for target qt_core_c
        echo >nul && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_autogen C:/Users/Freddy/RustroverProjects/isospin_simulation/target/debug/build/qt_core-5c4e8579972aed4a/out/c_lib_build/CMakeFiles/qt_core_c_autogen.dir/AutogenInfo.json Release
  [ 25%] Built target qt_core_c_autogen
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_core_c.dir\build.make /nologo -L                  CMakeFiles\qt_core_c.dir\depend
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_depends "NMake Makefiles" C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib C:\Users\Freddy\.cargo\registry\src\index.crates.io-6
f17d22bba15001f\qt_core-0.5.0\c_lib C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build\CMakeFiles\qt_core_c.dir\DependInfo.cmake "--color="
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_core_c.dir\build.make /nologo -L                  CMakeFiles\qt_core_c.dir\build
  [ 50%] Building CXX object CMakeFiles/qt_core_c.dir/qt_core_c_autogen/mocs_compilation.cpp.obj
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\qt_core_c.dir\qt_core_c_autogen\mocs_compilation.cpp.obj.d --working-dir=C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build --filter-prefix="Hinweis: Einlesen der Datei: " -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x86\cl.exe @C:\Users\Freddy\AppData\Local\Temp\nm5B3F.tmp
  mocs_compilation.cpp
  [ 75%] Building CXX object CMakeFiles/qt_core_c.dir/file1.cpp.obj
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\qt_core_c.dir\file1.cpp.obj.d --working-dir=C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_core-5c4e8579972aed4a\out\c_lib_build --filter-prefix="Hinweis: Einlesen der Datei: " -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x86\cl.exe @C:\Users\Freddy\AppData\Local\Temp\nm5B6F.tmp
  file1.cpp
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib\file1.cpp(26166): warning C4316: "QStaticByteArrayMatcherBase" : Das auf dem Heap zugeordnete Objekt ist möglicherweise nicht 16 ausgerichtet
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib\file1.cpp(60440): error C2665: "QCborStreamReader::StringResult<__int64>::StringResult": Keine überladene Funktion konnte alle Argumenttypen konvertieren
  C:\Qt\Qt5.14.0\5.14.0\msvc2017_64\include\QtCore\qcborstream.h(152): note: kann "QCborStreamReader::StringResult<__int64>::StringResult(QCborStreamReader::StringResult<__int64> &&)" sein
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib\file1.cpp(60440): note: "QCborStreamReader::StringResult<__int64>::StringResult(QCborStreamReader::StringResult<__int64> &&)" : Konvertierung von Argument 1 von "QCborStreamReader::StringResult<qsizetype>" in "QCborStreamReader::StringResult<__int64> &&" nicht möglich
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib\file1.cpp(60440): note: Ursache: Konvertierung von "QCborStreamReader::StringResult<qsizetype>" in "QCborStreamReader::StringResult<__int64>" nicht möglich
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib\file1.cpp(60440): note: Kein benutzerdefinierter Konvertierungsoperator verfügbar, der diese Konvertierung durchführen kann, oder der Operator kann nicht aufgerufen werden
  C:\Qt\Qt5.14.0\5.14.0\msvc2017_64\include\QtCore\qcborstream.h(152): note: oder "QCborStreamReader::StringResult<__int64>::StringResult(const QCborStreamReader::StringResult<__int64> &)"
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib\file1.cpp(60440): note: "QCborStreamReader::StringResult<__int64>::StringResult(const QCborStreamReader::StringResult<__int64> &)" : Konvertierung von Argument 1 von "QCborStreamReader::StringResult<qsizetype>" in "const QCborStreamReader::StringResult<__int64> &" nicht möglich
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib\file1.cpp(60440): note: Ursache: Konvertierung von "QCborStreamReader::StringResult<qsizetype>" in "const QCborStreamReader::StringResult<__int64>" nicht möglich
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib\file1.cpp(60440): note: Kein benutzerdefinierter Konvertierungsoperator verfügbar, der diese Konvertierung durchführen kann, oder der Operator kann nicht aufgerufen werden
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_core-0.5.0\c_lib\file1.cpp(60440): note: bei Anpassung der Argumentliste "(QCborStreamReader::StringResult<qsizetype>)"
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `qt_gui v0.5.0`                                                                                                                                                                                                                                                      

Caused by:
  process didn't exit successfully: `C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-c51469fbb170768c\build-script-build` (exit code: 1)
  --- stdout
  Current target is unknown: v5.14.0 on x86_64-windows-windows-msvc
  Known targets:
  * v5.9.7 on x86_64-linux-unix-gnu
  * v5.11.3 on x86_64-linux-unix-gnu
  * v5.12.2 on x86_64-linux-unix-gnu
  * v5.13.0 on x86_64-linux-unix-gnu
  * v5.14.0 on x86_64-linux-unix-gnu
  -- RITUAL_INCLUDE_PATH=C:/Qt/Qt5.14.0/5.14.0/msvc2017_64/include;C:/Qt/Qt5.14.0/5.14.0/msvc2017_64/include\QtGui;C:/Qt/Qt5.14.0/5.14.0/msvc2017_64/include\QtCore
  -- RITUAL_LIBRARY_PATH=C:/Qt/Qt5.14.0/5.14.0/msvc2017_64/lib
  -- RITUAL_LIBRARY_TYPE=STATIC
  -- RITUAL_LINKED_LIBS=Qt5Gui;Qt5Core
  -- RITUAL_CPP_LIB_VERSION=51400
  -- Configuring done (0.0s)
  -- Generating done (0.0s)
  -- Build files have been written to: C:/Users/Freddy/RustroverProjects/isospin_simulation/target/debug/build/qt_gui-9df96a1452f8b1aa/out/c_lib_build
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\Makefile2 /nologo -L                  clean
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_gui_c.dir\build.make /nologo -L                  CMakeFiles\qt_gui_c.dir\clean
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -P CMakeFiles\qt_gui_c.dir\cmake_clean.cmake
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_gui_c_autogen.dir\build.make /nologo -L                  CMakeFiles\qt_gui_c_autogen.dir\clean
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -P CMakeFiles\qt_gui_c_autogen.dir\cmake_clean.cmake
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -SC:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_gui-0.5.0\c_lib -BC:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build --check-build-system CMakeFiles\Makefile.cmake 0
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_progress_start C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build\CMakeFiles C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build\\CMakeFiles\progress.marks
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\Makefile2 /nologo -L                  all
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_gui_c_autogen.dir\build.make /nologo -L                  CMakeFiles\qt_gui_c_autogen.dir\depend
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_depends "NMake Makefiles" C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_gui-0.5.0\c_lib C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f
17d22bba15001f\qt_gui-0.5.0\c_lib C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build\CMakeFiles\qt_gui_c_autogen.dir\DependInfo.cmake "--color="
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_gui_c_autogen.dir\build.make /nologo -L                  CMakeFiles\qt_gui_c_autogen.dir\build
  [ 25%] Automatic MOC for target qt_gui_c
        echo >nul && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_autogen C:/Users/Freddy/RustroverProjects/isospin_simulation/target/debug/build/qt_gui-9df96a1452f8b1aa/out/c_lib_build/CMakeFiles/qt_gui_c_autogen.dir/AutogenInfo.json Release
  [ 25%] Built target qt_gui_c_autogen
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_gui_c.dir\build.make /nologo -L                  CMakeFiles\qt_gui_c.dir\depend
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_depends "NMake Makefiles" C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_gui-0.5.0\c_lib C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f
17d22bba15001f\qt_gui-0.5.0\c_lib C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build\CMakeFiles\qt_gui_c.dir\DependInfo.cmake "--color="
        "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX64\x86\nmake.exe"  -f CMakeFiles\qt_gui_c.dir\build.make /nologo -L                  CMakeFiles\qt_gui_c.dir\build
  [ 50%] Building CXX object CMakeFiles/qt_gui_c.dir/qt_gui_c_autogen/mocs_compilation.cpp.obj
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\qt_gui_c.dir\qt_gui_c_autogen\mocs_compilation.cpp.obj.d --working-dir=C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build --filter-prefix="Hinweis: Einlesen der Datei: " -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x86\cl.exe @C:\Users\Freddy\AppData\Local\Temp\nm5B8D.tmp
  mocs_compilation.cpp
  [ 75%] Building CXX object CMakeFiles/qt_gui_c.dir/file1.cpp.obj
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_cl_compile_depends --dep-file=CMakeFiles\qt_gui_c.dir\file1.cpp.obj.d --working-dir=C:\Users\Freddy\RustroverProjects\isospin_simulation\target\debug\build\qt_gui-9df96a1452f8b1aa\out\c_lib_build --filter-prefix="Hinweis: Einlesen der Datei: " -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1441~1.341\bin\Hostx64\x86\cl.exe @C:\Users\Freddy\AppData\Local\Temp\nm5BBD.tmp
  file1.cpp
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_gui-0.5.0\c_lib\file1.cpp(54183): error C2664: "void QOpenGLExtraFunctions::glDebugMessageCallback(GLDEBUGPROC,const void *)" : Konvertierung von Argument 1 von "void (__cdecl *)(unsigned int,unsigned int,unsigned int,unsigned int,int,const char *,const void *)" in "GLDEBUGPROC" nicht möglich
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_gui-0.5.0\c_lib\file1.cpp(54183): note: Diese Konvertierung erfordert eine reinterpret_cast-Umwandlung, eine C-Stil-Umwandlung oder eine in Klammern gesetzte Umwandlung im Funktionsstil.
  C:\Qt\Qt5.14.0\5.14.0\msvc2017_64\include\QtGui\qopenglextrafunctions.h(2213): note: Siehe Deklaration von "QOpenGLExtraFunctions::glDebugMessageCallback"
  C:\Users\Freddy\.cargo\registry\src\index.crates.io-6f17d22bba15001f\qt_gui-0.5.0\c_lib\file1.cpp(54183): note: bei Anpassung der Argumentliste "(void (__cdecl *)(unsigned int,unsigned int,unsigned int,unsigned int,int,const char *,const void *), const void *)"
```

**Comment by Zane-Liao** [comment]
I'm guessing it's a Windows platform incompatibility?
